### ISSUE TITLE
Cannot switch from JS to Handlebars in Webstorm

### ISSUE THREAD

**Issue by emkman** [mfedko/idea-file-language#2]
I have files that must end in .js due to my server environment but they are actually Handlebars HTML templates. An example filename would be `users.html.js`. I thought this plugin would be the perfect fix, however when I go to switch the language to Handlebars using the menu in the bottom right corner, the language immediately reverts back to Javascript. My Webstorm version is 11.0.3.

**Comment by mfedko** [comment]
I'm afraid it works only for "unknown" or text files, IDEA overrides known file types itself.

**Comment by emkman** [comment]
No problem, I actually solved my problem by adding a custom file extension pattern to the Handlebars template settings. Thanks!
