### ISSUE TITLE
Popup window small and not resizable

### ISSUE THREAD

**Issue by vadviktor** [mfedko/idea-file-language#3]
I am not familiar with Idea plugin development and I'm only scratching the surface of Java, that's why I report rather than dive in head on to create a pull request and fix my issue. :)

Using Intellij 2016.1.2 on Xubuntu 16.04 with Oracle JDK 8 (x64).

When I open a file that has no extension and no associated file type setting in the IDE I can change the file language through the "File language" action
![still_small](https://cloud.githubusercontent.com/assets/238703/15467655/94f3a7d6-20d7-11e6-9117-e2299961fc0b.jpg)
(which I sadly cannot assign a key shortcut). That popup is only 2-3 lines high and I cannot resize it.

The same issue is present when I use the lower right corner action in the status bar:
![small](https://cloud.githubusercontent.com/assets/238703/15467635/83fe54ee-20d7-11e6-8bf8-0529ff8635e3.jpg)

It's great that I can search in it, but I'd appreciate at least 5-10 lines height so I can see more broadly.

Also it is not the main purpose of this report, but I also wish to be able to assign a key shortcut to this action.

Thanks for this great plugin! :heart:

**Comment by mfedko** [comment]
I've uloaded 0.1.2 version with small UI fixes. 
It still doesn't allow to resize popup.

You can try to call popup via ctrl-shift-a -> search File Language

**Comment by vadviktor** [comment]
Hey @mfedko , thanks for the efforts! :)

Though, the popup(s) are all the same height, there are no sign of changes :(

What changes should I see now?
Could you make those popups' height at least double?

**Comment by GabLeRoux** [comment]
Can't be reproduced in `v0.1.1` with Intellij IDEA `2018.3.5`

```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
```

![image](https://user-images.githubusercontent.com/1264761/54150363-a598db80-440e-11e9-9fff-1dfb38f9cf74.png)

window height can't be resized, but it's long enough here.
