### ISSUE TITLE
Overriding language breaks 'Scroll from Source'

### ISSUE THREAD

**Issue by crazygolem** [mfedko/idea-file-language#4]
Once the language of a file has been overridden, the 'Scroll from Source' button won't work for that file.
Reverting to the original language doesn't fix this (I suppose the language is then still overridden, not actually reset).

Plugin version: 0.1.1
IntelliJ version: Ultimate 2017.3 (build #IU-173.3942.27)

**Comment by mfedko** [comment]
Hi, sorry for the late response.

What exactly is "Scroll from Source" button? In idea 2018.1 I can see 'Autoscroll from Source' option in project tab settings. It seems to be working with 0.1.3 build of plugin.

**Comment by crazygolem** [comment]
I was talking about the crosshair button that you can click to get to the currently opened file in the Project panel: ![Scroll from Source](https://www.jetbrains.com/help/img/idea/2018.1/icon_scroll_from_source_on_title_bar.png) (see also [Project Tool Window](https://www.jetbrains.com/help/idea/project-tool-window.html#title_bar_buttons))

I did not test again since reporting the bug, but I'll give it a try.

**Comment by crazygolem** [comment]
Tested successfully. This issue can be closed.

**Versions**
Plugin: 0.1.3
IntelliJ: Ultimate 2018.1 (#IU-181.4203.550)
