### ISSUE TITLE
Cannot switch language to Python

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [mfedko/idea-file-language#5]
I am following [this tutorial]( https://codevoid.io/hosting-a-python-web-service-in-gunicorn-and-docker.html )

The file in question is `gunicorn.conf`, which despite being a `.conf` file is Python code with the following content:

```py
import multiprocessing

# listen to port 5858 on all available network interfaces
bind = "0.0.0.0:5858"

# Run the aiohttp app in multiple processes
workers = multiprocessing.cpu_count() * 2 + 1

# Use the correct worker class for aiohttp - this will change is using a different framework
worker_class = 'aiohttp.worker.GunicornWebWorker'
```

This file is incorrectly detected to be `HOCON`, and I cannot switch the language via the drop-down to `Python` or any language.

- Override File Language is definitely installed
- Intellij 2018.1

**Comment by mfedko** [comment]
Hi, did you install the Python plugin?
Perhaps, I've prepared a new build 0.1.3 for idea 2018.1. Give it a try as it gets Jetbrains approve.
