### ISSUE TITLE
Add keymap to select language

### ISSUE THREAD

**Issue by crazygolem** [mfedko/idea-file-language#6]
IntelliJ provides a keymap to change the language of scratches:
![image](https://user-images.githubusercontent.com/433553/42270078-3ef7fd1e-7f80-11e8-893f-f58d1fd2aeb0.png)
![image](https://user-images.githubusercontent.com/433553/42270222-96937738-7f80-11e8-9b63-7337ec380e2a.png)

This only works natively for scratches though, so the idea-file-language plugin is still relevant for all other files. However it would be nice if I could invoke the same keystroke to change the language with the plugin when I'm not editing scratches.

**Comment by mfedko** [comment]
Command can be called from run actions- ctrl-shift-a -> File language
