### ISSUE TITLE
Downgrade with IntelliJ Idea Ultimate 2018.2+

### ISSUE THREAD

**Issue by jrobichaud** [mfedko/idea-file-language#7]
When upgrading to 2018.2 this plugin is asked to be downgraded.

![image](https://user-images.githubusercontent.com/12142702/44271799-1d9c7b80-a209-11e8-85aa-9b7cbe220c66.png)

**Comment by crazygolem** [comment]
After downgrading, the language selection pane shows "Nothing here":
![image](https://user-images.githubusercontent.com/433553/45809644-f8e46980-bcc8-11e8-8024-9b800c51ff7d.png)

I tried by forcing using the latest version (by manually editing the plugin's compatibility attribute in the manifest) with the same result.

**Comment by jrobichaud** [comment]
It does the same thing with 2018.3.

**Comment by GabLeRoux** [comment]
I can't reproduce the empty language list regression using latest Intellij Idea version `2018.3.5`:

```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
```

![language list](https://user-images.githubusercontent.com/1264761/54148188-286b6780-440a-11e9-9383-bfcea4071c62.png)

Plugin version: `v0.1.1` so this is indeed not the latest `v0.1.3`, but the `Nothing here` problem seems to be gone.
