### ISSUE TITLE
Cannot override language if intellij File Types is set

### ISSUE THREAD

**Issue by GabLeRoux** [mfedko/idea-file-language#8]
With plugin `idea-file-language` version `v0.1.1`, if there is a `File Types` associated with the current file, the extension override from this plugin doesn't take effect.

```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
```

Compared to #7 where the list says `Nothing here`, I do see languages and I can swap a language, but it only works for files that are considered `Play Text` by Intellij.

## How to reproduce

1. Create an `.sql` file
2. Try to change that default `mysql` sql association to `Microsft SQL`
3. Once clicked, the language is still mysql

## Workarounds

a. Add `.txt` to your file, then use the plugin to change set the language. _This is a very bad workaround_
b. Remove file types associated with the file you're editing in the settings. _This is also very bad, as defaults are great_

**Comment by GabLeRoux** [comment]
I don't have much experience in Intellij plugin development, but I'd like to contribute. I use this plugin a lot so if @mfedko you have an idea on what could be done for this, I would be very happy to give a hand.

If anyone has an idea on how to solve this, please provide details. :)
That's probably an extra check to do in `com.github.mfedko.idea.plugins.filelanguage.FileLanguagePanel#update`

**Comment by mfedko** [comment]
Unfortunatelly IDEA allow this only for "unknown" or txt files.

**Comment by GabLeRoux** [comment]
I've created [the following issue](https://youtrack.jetbrains.com/issue/IDEA-210363) so maybe Jetbrains can do something about it.
